# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: EKbana ML Study Group
email: 
description: >- # this means to ignore newlines until "baseurl:"
  EKbana Machine Learning Study Group.
  
title_separator: "|"
twitter_username: ekbanas
github_username: ekbanasolutions
minimal_mistakes_skin: contrast # 'air', 'contrast'

# Do not mess with this
baseurl: ""
url: "https://ekbanaml.github.io"

search: true
breadcrumbs: true

words_per_minute: 200

# Assets
logo: /assets/images/ekbana/ekbanalogo.png
teaser: /assets/images/ekbana/ekbana.jpg
carousel: /assets/images/ekbana/ekbana.jpg
# For pages that don’t have a header.image assigned in their YAML Front Matter
og_image: /assets/images/ekbana/logo.png


# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

remote_theme: mmistakes/minimal-mistakes

# Outputting
# permalink: /:slugified_categories/:title/ # uncomment this when GitHub pages updates to Jekyll 4.1  
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Kathmandu # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages


twitter:
  username: "ekbanas"

# google_site_verification: "code"


social:
  type:  "Organization" # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/ekbanas"
    - "https://www.facebook.com/ekbana"
    - "https://instagram.com/ekbana_solutions/"
    - "https://www.linkedin.com/company/ekbana-solutions-pte--ltd/"

# Analytics
analytics:
 provider: "google-gtag"
 google:
   tracking_id: "UA-161429185-3"
   anonymize_ip: false # default

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - GUIDELINE.md
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# author:
#   name   : "EKbana"
#   avatar : "/assets/images/bio-photo.jpg"
#   bio    : "My awesome biography constrained to a sentence or two goes here."
#   links:
#     - label: "Website"
#       icon: "fas fa-fw fa-link"
#       url: "https://"
#     - label: "Twitter"
#       icon: "fab fa-fw fa-twitter-square"
#       url: "https://twitter.com/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ekbanas"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ekbanasolutions"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ekbana_solutions"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      toc: true
      toc_icon: "rocket"
      toc_sticky: "false"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
